### ISSUE TITLE
thoughts on oortcloud/node-ddp-client

### ISSUE THREAD

**Issue by morenoh149** [spencercarli/meteor-todos-react-native-2#12]
There are no comments on the blog so I'll post my question here. How does https://github.com/oortcloud/node-ddp-client compare to https://github.com/hharnisc/node-ddp-client ?

**Comment by spencercarli** [comment]
Hey, I'm not 100% sure but I think oortcloud/node-ddp-client has some requirements that may not be available in React Native (not all node modules are available).

I'm not sure if that is still the case though as there have been a lot of updates to React Native since I started working with it. I chose hharnisc's package for this project because I'm familiar with it :smile:
